# Generated by Selenium IDE
# Выделение параметров в методах.
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestAddressadd():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.driver.maximize_window()
        self.driver.implicitly_wait(30)
        self.vars = {}

    def open_home_page(self):
        # Открытие страницы авторизации адресной книги.
        self.driver.get("http://localhost/addressbook/")

    def authorization(self, username, password):
        # Авторизация.
        self.driver.find_element(By.NAME, "user").click()
        self.driver.find_element(By.NAME, "user").send_keys(username)
        self.driver.find_element(By.NAME, "pass").click()
        self.driver.find_element(By.NAME, "pass").send_keys(password)
        self.driver.find_element(By.XPATH, "//input[@value=\'Login\']").click()

    def open_contact_creation_page(self):
        # Открытие страницы создания нового контакта.
        self.driver.find_element(By.LINK_TEXT, "add new").click()

    def names(self, first_name, middle_name, last_name, nickname):
        # Имена.
        self.driver.find_element(By.NAME, "firstname").click()
        self.driver.find_element(By.NAME, "firstname").send_keys(first_name)
        self.driver.find_element(By.NAME, "middlename").click()
        self.driver.find_element(By.NAME, "middlename").send_keys(middle_name)
        self.driver.find_element(By.NAME, "lastname").click()
        self.driver.find_element(By.NAME, "lastname").send_keys(last_name)
        self.driver.find_element(By.NAME, "nickname").click()
        self.driver.find_element(By.NAME, "nickname").send_keys(nickname)

    def company_data(self, company_short_name, company_full_name, company_address):
        # Работа.
        self.driver.find_element(By.NAME, "title").click()
        self.driver.find_element(By.NAME, "title").send_keys(company_short_name)
        self.driver.find_element(By.NAME, "company").click()
        self.driver.find_element(By.NAME, "company").send_keys(company_full_name)
        self.driver.find_element(By.NAME, "address").click()
        self.driver.find_element(By.NAME, "address").send_keys(company_address)

    def phones(self, home_tel, mobile_tel, work_tel, fax):
        # Телефоны.
        self.driver.find_element(By.NAME, "home").click()
        self.driver.find_element(By.NAME, "home").send_keys(home_tel)
        self.driver.find_element(By.NAME, "mobile").click()
        self.driver.find_element(By.NAME, "mobile").send_keys(mobile_tel)
        self.driver.find_element(By.NAME, "work").click()
        self.driver.find_element(By.NAME, "work").send_keys(work_tel)
        self.driver.find_element(By.NAME, "fax").click()
        self.driver.find_element(By.NAME, "fax").send_keys(fax)

    def mails(self, mail01, mail02, mail03):
        # Электронные почты.
        self.driver.find_element(By.NAME, "email").click()
        self.driver.find_element(By.NAME, "email").send_keys(mail01)
        self.driver.find_element(By.NAME, "email2").click()
        self.driver.find_element(By.NAME, "email2").send_keys(mail02)
        self.driver.find_element(By.NAME, "email3").click()
        self.driver.find_element(By.NAME, "email3").send_keys(mail03)

    def homepage(self, homepage01):
        # Урл домашней страницы.
        self.driver.find_element(By.NAME, "homepage").click()
        self.driver.find_element(By.NAME, "homepage").send_keys(homepage01)

    def dates(self):
        # Даты.
        self.driver.find_element(By.NAME, "bday").click()
        dropdown = self.driver.find_element(By.NAME, "bday")
        dropdown.find_element(By.XPATH, "//option[. = '1']").click()
        self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(61) > option:nth-child(3)").click()
        self.driver.find_element(By.NAME, "bmonth").click()
        dropdown = self.driver.find_element(By.NAME, "bmonth")
        dropdown.find_element(By.XPATH, "//option[. = 'January']").click()
        self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(62) > option:nth-child(2)").click()
        self.driver.find_element(By.NAME, "byear").click()
        self.driver.find_element(By.NAME, "byear").send_keys("1970")
        self.driver.find_element(By.NAME, "aday").click()
        dropdown = self.driver.find_element(By.NAME, "aday")
        dropdown.find_element(By.XPATH, "//option[. = '1']").click()
        self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(66) > option:nth-child(3)").click()
        self.driver.find_element(By.NAME, "amonth").click()
        dropdown = self.driver.find_element(By.NAME, "amonth")
        dropdown.find_element(By.XPATH, "//option[. = 'January']").click()
        self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(67) > option:nth-child(2)").click()
        self.driver.find_element(By.NAME, "ayear").click()
        self.driver.find_element(By.NAME, "ayear").send_keys("2020")

    def more_info(self, additional_address01, additional_phone01, notes):
        # Дополнительная информация.
        self.driver.find_element(By.NAME, "address2").click()
        self.driver.find_element(By.NAME, "address2").send_keys(additional_address01)
        self.driver.find_element(By.NAME, "phone2").click()
        self.driver.find_element(By.NAME, "phone2").send_keys(additional_phone01)
        self.driver.find_element(By.NAME, "notes").click()
        self.driver.find_element(By.NAME, "notes").send_keys(notes)
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(87)").click()

    def return_to_home_page(self):
        # Возврат на домашнюю страницу.
        self.driver.find_element(By.LINK_TEXT, "home").click()

    def logout(self):
        # Логаут.
        self.driver.find_element(By.LINK_TEXT, "Logout").click()

    def test_addressadd(self):
        self.open_home_page()
        self.authorization(username="admin", password="secret")
        self.open_contact_creation_page()
        self.names(first_name="FIRST_NAME", middle_name="MIDDLE_NAME", last_name="LAST_NAME", nickname="nickfield")
        self.company_data(company_short_name="titrlfield", company_full_name="companyField",
                          company_address="Нижний Новгород, пр. Ленина, 88")
        self.phones(home_tel="home_tel", mobile_tel="mob_tel", work_tel="work_tel", fax="889090808058")
        self.mails(mail01="mail1@mail.mail", mail02="mail2@mail.mail", mail03="mail3@mail.mail")
        self.homepage(homepage01="homepage_url")
        self.dates()
        self.more_info(additional_address01="secondary_address", additional_phone01="secondary_home_field",
                       notes="secondary_note_field")
        self.return_to_home_page()
        self.logout()

    def teardown_method(self, method):
        self.driver.quit()
