# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from group1_16 import Group
from application import Application
import pytest


class TestTestaddgroup():
    def setup_method(self, method):
        self.app = Application()

    def test_testaddgroup(self):
        self.app.login(username="admin", password="secret")
        self.app.create_group(Group(name="Name_group01", header="group_header01", footer="group_footer01"))
        self.app.logout()

    def test_testaddemptygroup(self):
        self.app.login(username="admin", password="secret")
        self.app.create_group(Group(name="", header="", footer=""))
        self.app.logout()

    def teardown_method(self, method):
        self.app.destroy()
